services:
  web:
    build: .
    container_name: capsula_web
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
       DATABASE_URL: mysql://root:isaac@12@db:3306/capsula_db?serverVersion=8.3&charset=utf8mb4
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.3
    container_name: capsula_db
    environment:
      MYSQL_DATABASE: capsula_db
      MYSQL_ROOT_PASSWORD: isaac@12
    ports:
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

